### ISSUE TITLE
Add a CSS property to change the margin between icons

### ISSUE THREAD

**Issue by alejost848** [mgibas/paper-rating#1]
Hello, thanks for making this element, it's really nice and simple. I'm using it at the moment and I thought of something that could improve it. Right now there's no way of changing the margin between the icons, so I realized that it can be exposed through a CSS property. I'm working on a pull request so we can discuss it.

**Comment by alejost848** [comment]
This is how it could be used.
```css
paper-rating {
  --paper-rating-icon-margin: -2px;
}
```
I'm not sure if the property naming is right though. What do you think?

**Comment by mgibas** [comment]
Im good with that, though wouldn't it be better to just expose mixin for this icon rather than margin only ?

**Comment by alejost848** [comment]
Well, I can't think of any other property that I'd use for the element other than margin, but you might be right, I was just thinking about my use case, since the element already looks how I need it to be. Exposing the mixing would be more complete and more useful in other people's use cases.

I updated the pull request, please check if it's implemented correctly.

**Comment by mgibas** [comment]
Perfect, thanks a lot!
